AllCops:
  TargetRubyVersion: 2.4
  Includes:
    - Rakefile
    - config.ru
    - Gemfile
  Excludes:
    - db/**
    - config/**
    - script/**
Lint/Debugger:
  Exclude:
    - spec/rails_helper.rb
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Max: 15
Style/ClassAndModuleChildren:
  Enabled: false
